# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dab739b0c208e1f161a4b148ea0b8335203d8dba3924620de61d1a511b350b0eab112acf2cb2fbb83baf9493271882a309ad1656e19a7da05ee0059cb524d6f8
  google_key: 'AIzaSyAxM-N66aK2aCq0yhxQrJJZMh-XYcEauUk&'

test:
  secret_key_base: c04bcfd1b2f8eea61040e6792b7faa6bd0d25290b8b45994291044c96b257c57c732a111c9994953208d78b98e21aa31fb593ff9e3d068534e377a23e0e531f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_key: <%= ENV["GOOGLE_KEY"] %>


